package luoyi.android.com.wsfzzs.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import luoyi.android.com.wsfzzs.sql.bean.SBDataStatistics;

import luoyi.android.com.wsfzzs.sql.SBDataStatisticsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sBDataStatisticsDaoConfig;

    private final SBDataStatisticsDao sBDataStatisticsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sBDataStatisticsDaoConfig = daoConfigMap.get(SBDataStatisticsDao.class).clone();
        sBDataStatisticsDaoConfig.initIdentityScope(type);

        sBDataStatisticsDao = new SBDataStatisticsDao(sBDataStatisticsDaoConfig, this);

        registerDao(SBDataStatistics.class, sBDataStatisticsDao);
    }
    
    public void clear() {
        sBDataStatisticsDaoConfig.clearIdentityScope();
    }

    public SBDataStatisticsDao getSBDataStatisticsDao() {
        return sBDataStatisticsDao;
    }

}
