package luoyi.android.com.wsfzzs.sql;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import luoyi.android.com.wsfzzs.sql.bean.SBDataStatistics;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SBDATA_STATISTICS".
*/
public class SBDataStatisticsDao extends AbstractDao<SBDataStatistics, Long> {

    public static final String TABLENAME = "SBDATA_STATISTICS";

    /**
     * Properties of entity SBDataStatistics.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Periods = new Property(1, String.class, "periods", false, "PERIODS");
        public final static Property LotteryNumber = new Property(2, String.class, "lotteryNumber", false, "LOTTERY_NUMBER");
        public final static Property LotteryTime = new Property(3, long.class, "lotteryTime", false, "LOTTERY_TIME");
    }


    public SBDataStatisticsDao(DaoConfig config) {
        super(config);
    }
    
    public SBDataStatisticsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SBDATA_STATISTICS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PERIODS\" TEXT," + // 1: periods
                "\"LOTTERY_NUMBER\" TEXT," + // 2: lotteryNumber
                "\"LOTTERY_TIME\" INTEGER NOT NULL );"); // 3: lotteryTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SBDATA_STATISTICS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SBDataStatistics entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String periods = entity.getPeriods();
        if (periods != null) {
            stmt.bindString(2, periods);
        }
 
        String lotteryNumber = entity.getLotteryNumber();
        if (lotteryNumber != null) {
            stmt.bindString(3, lotteryNumber);
        }
        stmt.bindLong(4, entity.getLotteryTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SBDataStatistics entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String periods = entity.getPeriods();
        if (periods != null) {
            stmt.bindString(2, periods);
        }
 
        String lotteryNumber = entity.getLotteryNumber();
        if (lotteryNumber != null) {
            stmt.bindString(3, lotteryNumber);
        }
        stmt.bindLong(4, entity.getLotteryTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SBDataStatistics readEntity(Cursor cursor, int offset) {
        SBDataStatistics entity = new SBDataStatistics( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // periods
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lotteryNumber
            cursor.getLong(offset + 3) // lotteryTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SBDataStatistics entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPeriods(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLotteryNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLotteryTime(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SBDataStatistics entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SBDataStatistics entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SBDataStatistics entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
